#ifndef KK_RESOURCES_H
#define KK_RESOURCES_H


#include <allegro.h>


typedef enum {
  KK_IMG_SWORD_STAB_2,
  KK_IMG_SWORD_STAB_4,
  KK_IMG_SWORD_STAB_3,
  KK_IMG_SWORD_STAB_1,
  KK_IMG_SWORD_HOLD_2,
  KK_IMG_SWORD_HOLD_4,
  KK_IMG_SWORD_HOLD_3,
  KK_IMG_SWORD_HOLD_1,
  KK_IMG_SHIELD_2,
  KK_IMG_SHIELD_4,
  KK_IMG_SHIELD_3,
  KK_IMG_SHIELD_1,
  KK_IMG_TITLE,
  KK_IMG_CHOMPER_BITE_2,
  KK_IMG_CHOMPER_BITE_4,
  KK_IMG_CHOMPER_BITE_5,
  KK_IMG_CHOMPER_BITE_3,
  KK_IMG_CHOMPER_BITE_1,
  KK_IMG_CHOMPER_STAND_2,
  KK_IMG_CHOMPER_STAND_3,
  KK_IMG_CHOMPER_STAND_1,
  KK_IMG_HERO_HURT_2,
  KK_IMG_HERO_HURT_4,
  KK_IMG_HERO_HURT_3,
  KK_IMG_HERO_HURT_1,
  KK_IMG_HERO_DIE_2,
  KK_IMG_HERO_DIE_4,
  KK_IMG_HERO_DIE_5,
  KK_IMG_HERO_DIE_3,
  KK_IMG_HERO_DIE_1,
  KK_IMG_HERO_ATTACK_2,
  KK_IMG_HERO_ATTACK_4,
  KK_IMG_HERO_ATTACK_3,
  KK_IMG_HERO_ATTACK_1,
  KK_IMG_HERO_STAND_2,
  KK_IMG_HERO_STAND_3,
  KK_IMG_HERO_STAND_1,
  KK_IMG_ARCHER_2,
  KK_IMG_ARCHER_3,
  KK_IMG_ARCHER_1,
  KK_IMG_ITEMS_EMPTYHEART,
  KK_IMG_ITEMS_HEART,
  KK_IMG_ITEMS_MONEYBAG,
  KK_IMG_TERRAIN_DOWNSTAIRS,
  KK_IMG_TERRAIN_WATER,
  KK_IMG_TERRAIN_DIRT,
  KK_IMG_TERRAIN_ICE,
  KK_IMG_TERRAIN_PATH,
  KK_IMG_TERRAIN_SPIRE,
  KK_IMG_TERRAIN_OAK,
  KK_IMG_TERRAIN_UPSTAIRS,
  KK_IMG_TERRAIN_SNOW,
  KK_IMG_TERRAIN_EVERGREEN,
  KK_IMG_TERRAIN_GRASS,
  KK_IMG_HAMMER_SWING_2,
  KK_IMG_HAMMER_SWING_4,
  KK_IMG_HAMMER_SWING_3,
  KK_IMG_HAMMER_SWING_1,
  KK_IMG_HAMMER_HOLD_2,
  KK_IMG_HAMMER_HOLD_4,
  KK_IMG_HAMMER_HOLD_3,
  KK_IMG_HAMMER_HOLD_1,
  KK_IMG_BOW_DRAW_2,
  KK_IMG_BOW_DRAW_3,
  KK_IMG_BOW_DRAW_1,
  KK_IMG_BOW_HOLD_2,
  KK_IMG_BOW_HOLD_4,
  KK_IMG_BOW_HOLD_3,
  KK_IMG_BOW_HOLD_1,
  KK_IMG_GIANT_2,
  KK_IMG_GIANT_3,
  KK_IMG_GIANT_1,
  KK_IMG_ARROW,
  KK_IMG_SHORE_SNOW_INSIDECORNER,
  KK_IMG_SHORE_SNOW_OUTSIDECORNER,
  KK_IMG_SHORE_SNOW_SHORE,
  KK_IMG_SHORE_GRASS_INSIDECORNER,
  KK_IMG_SHORE_GRASS_OUTSIDECORNER,
  KK_IMG_SHORE_GRASS_SHORE,
  KK_IMG_HELP,
  KK_IMG_GAMEOVER,
  KK_IMG_PALETTE,
  KK_IMG_NINJA_2,
  KK_IMG_NINJA_3,
  KK_IMG_NINJA_1,
  KK_NUMBER_OF_IMAGES
} KK_IMAGES;


typedef enum {
  KK_SND_MONEY,
  KK_SND_ARROW_HIT,
  KK_SND_ARROW_FLY,
  KK_SND_HEART,
  KK_SND_GASP,
  KK_SND_SWORD,
  KK_SND_HAMMER,
  KK_SND_CHOMP,
  KK_NUMBER_OF_SOUNDS
} KK_SOUNDS;


void kk_init_resources();
void kk_free_resources();

PALETTE * kk_get_palette();

inline BITMAP * kk_get_image(int image);

void kk_play_sound(int sound);

void kk_toggle_sound();
bool kk_sound_enabled();


#endif
