/* Allegro datafile object indexes, produced by grabber v4.4.0, Unix */
/* Datafile: /home/couzelis/Projects/Kwest Kingdom/kwestkingdom/res/resources.dat */
/* Date: Sat Jan 30 09:36:31 2010 */
/* Do not hand edit! */

#define ARROW_FLY_SOUND                  0        /* SAMP */
#define ARROW_HIT_SOUND                  1        /* SAMP */
#define CHOMP_SOUND                      2        /* SAMP */
#define GASP_SOUND                       3        /* SAMP */
#define HAMMER_ATTACK_SOUND              4        /* SAMP */
#define HEART_SOUND                      5        /* SAMP */
#define MONEY_SOUND                      6        /* SAMP */
#define SWORD_ATTACK_SOUND               7        /* SAMP */
#define ARCHER_01_BMP                    8        /* BMP  */
#define ARCHER_02_BMP                    9        /* BMP  */
#define ARCHER_03_BMP                    10       /* BMP  */
#define ARROW_01_BMP                     11       /* BMP  */
#define BOW_01_BMP                       12       /* BMP  */
#define BOW_02_BMP                       13       /* BMP  */
#define BOW_03_BMP                       14       /* BMP  */
#define BOW_04_BMP                       15       /* BMP  */
#define BOW_ATTACK_01_BMP                16       /* BMP  */
#define BOW_ATTACK_02_BMP                17       /* BMP  */
#define BOW_ATTACK_03_BMP                18       /* BMP  */
#define CHOMPER_01_BMP                   19       /* BMP  */
#define CHOMPER_02_BMP                   20       /* BMP  */
#define CHOMPER_03_BMP                   21       /* BMP  */
#define CHOMPER_ATTACK_01_BMP            22       /* BMP  */
#define CHOMPER_ATTACK_02_BMP            23       /* BMP  */
#define CHOMPER_ATTACK_03_BMP            24       /* BMP  */
#define CHOMPER_ATTACK_04_BMP            25       /* BMP  */
#define CHOMPER_ATTACK_05_BMP            26       /* BMP  */
#define GAME_OVER_01_BMP                 27       /* BMP  */
#define GIANT_01_BMP                     28       /* BMP  */
#define GIANT_02_BMP                     29       /* BMP  */
#define GIANT_03_BMP                     30       /* BMP  */
#define HAMMER_01_BMP                    31       /* BMP  */
#define HAMMER_02_BMP                    32       /* BMP  */
#define HAMMER_03_BMP                    33       /* BMP  */
#define HAMMER_04_BMP                    34       /* BMP  */
#define HAMMER_ATTACK_01_BMP             35       /* BMP  */
#define HAMMER_ATTACK_02_BMP             36       /* BMP  */
#define HAMMER_ATTACK_03_BMP             37       /* BMP  */
#define HAMMER_ATTACK_04_BMP             38       /* BMP  */
#define HELP_01_BMP                      39       /* BMP  */
#define HERO_01_BMP                      40       /* BMP  */
#define HERO_02_BMP                      41       /* BMP  */
#define HERO_03_BMP                      42       /* BMP  */
#define HERO_ATTACK_01_BMP               43       /* BMP  */
#define HERO_ATTACK_02_BMP               44       /* BMP  */
#define HERO_ATTACK_03_BMP               45       /* BMP  */
#define HERO_ATTACK_04_BMP               46       /* BMP  */
#define HERO_DEAD_01_BMP                 47       /* BMP  */
#define HERO_DEAD_02_BMP                 48       /* BMP  */
#define HERO_DEAD_03_BMP                 49       /* BMP  */
#define HERO_DEAD_04_BMP                 50       /* BMP  */
#define HERO_DEAD_05_BMP                 51       /* BMP  */
#define HERO_HURT_01_BMP                 52       /* BMP  */
#define HERO_HURT_02_BMP                 53       /* BMP  */
#define HERO_HURT_03_BMP                 54       /* BMP  */
#define HERO_HURT_04_BMP                 55       /* BMP  */
#define ITEM_HEART_01_BMP                56       /* BMP  */
#define ITEM_HEART_EMPTY_01_BMP          57       /* BMP  */
#define ITEM_MONEYBAG_01_BMP             58       /* BMP  */
#define NINJA_01_BMP                     59       /* BMP  */
#define NINJA_02_BMP                     60       /* BMP  */
#define NINJA_03_BMP                     61       /* BMP  */
#define SHIELD_01_BMP                    62       /* BMP  */
#define SHIELD_02_BMP                    63       /* BMP  */
#define SHIELD_03_BMP                    64       /* BMP  */
#define SHIELD_04_BMP                    65       /* BMP  */
#define SHORE_01_BMP                     66       /* BMP  */
#define SHORE_ICE_01_BMP                 67       /* BMP  */
#define SHORE_ICE_INSIDE_CORNER_01_BMP   68       /* BMP  */
#define SHORE_ICE_OUTSIDE_CORNER_01_BMP  69       /* BMP  */
#define SHORE_INSIDE_CORNER_01_BMP       70       /* BMP  */
#define SHORE_OUTSIDE_CORNER_01_BMP      71       /* BMP  */
#define SWORD_01_BMP                     72       /* BMP  */
#define SWORD_02_BMP                     73       /* BMP  */
#define SWORD_03_BMP                     74       /* BMP  */
#define SWORD_04_BMP                     75       /* BMP  */
#define SWORD_ATTACK_01_BMP              76       /* BMP  */
#define SWORD_ATTACK_02_BMP              77       /* BMP  */
#define SWORD_ATTACK_03_BMP              78       /* BMP  */
#define SWORD_ATTACK_04_BMP              79       /* BMP  */
#define TERRAIN_DIRT_01_BMP              80       /* BMP  */
#define TERRAIN_EVERGREEN_01_BMP         81       /* BMP  */
#define TERRAIN_GRASS_01_BMP             82       /* BMP  */
#define TERRAIN_ICE_01_BMP               83       /* BMP  */
#define TERRAIN_PATH_01_BMP              84       /* BMP  */
#define TERRAIN_ROCK_01_BMP              85       /* BMP  */
#define TERRAIN_SNOW_01_BMP              86       /* BMP  */
#define TERRAIN_STAIRS_DOWN_01_BMP       87       /* BMP  */
#define TERRAIN_STAIRS_UP_01_BMP         88       /* BMP  */
#define TERRAIN_TREE_01_BMP              89       /* BMP  */
#define TERRAIN_WATER_01_BMP             90       /* BMP  */
#define TITLE_01_BMP                     91       /* BMP  */
#define PALETTE_PAL                      92       /* PAL  */

