all:
	 rm -rf Linux/share/kwestkingdom/img
	 rm -rf Linux/share/kwestkingdom/snd
	 cp -r res/img Linux/share/kwestkingdom/
	 cp -r res/snd Linux/share/kwestkingdom/
	 make -C src

clean:
	 make -C src clean

